### ISSUE TITLE
Not showing in modules zabbix 6.4.1

### ISSUE THREAD

**Issue by dhapheto** [gr8b/zabbix-module-sqlexplorer#4]
Hi,

I have upload this modules in /user/share/zabbix/modules/zabbix-module-sqlexplorer/ but in GUI zabbix modules menu not show SQL Explorer module. Could you please help me ?

**Comment by gr8b** [comment]
You should modify manifest.json property [manifest_version](https://github.com/gr8b/zabbix-module-sqlexplorer/blob/main/manifest.json#LL2C3-L2C19) to 2, to module be discoverable by Zabbix version 6.4+. As is written in module README, current version is compatible with version 5.x - 6.2.

**Comment by gr8b** [comment]
Support for Zabbix version 6.4 and newer is added to module version 1.8
