### ISSUE TITLE
http://ip/zabbix/zabbix.php?action=sqlexplorer.form zabbix 6.4.1

### ISSUE THREAD

**Issue by cervelo37** [gr8b/zabbix-module-sqlexplorer#5]
Hi

I have installed sqlexplorer but I have this error
http://ip/zabbix/zabbix.php?action=sqlexplorer.form
I have the latest version of zabbix 6.4.1
![image](https://github.com/gr8b/zabbix-module-sqlexplorer/assets/133645980/4bc83546-317f-41d4-9854-362c6f52b364)

Can you help me ?

**Comment by gr8b** [comment]
Support for Zabbix version 6.4+ is added in version 1.8.
