### ISSUE TITLE
 PHP Fatal error

### ISSUE THREAD

**Issue by amarildosertorio** [gr8b/zabbix-module-sqlexplorer#8]
Oracle Linux Server release 8.9
Zabbix 6.0.25
PHP 8.2.13
Apache 2.4.37
SqlExplorer 1.9

PHP Fatal error:  Cannot make static method CController::getValidationRules() non static in class Modules\SqlExplorer\Actions\SqlForm in /usr/share/zabbix/modules/zabbix-module-sqlexplorer/actions/SqlForm.php on line 21

**Comment by gr8b** [comment]
@amarildosertorio can you confirm that Zabbix source is not modified?
Zabbix `6.0.26rc1` with module `1.9` and PHP `8.2.4` runs without any issue.

**Comment by gr8b** [comment]
My bad, checked for `6.0.25` and it fails. Fixed in [v1.10](https://github.com/gr8b/zabbix-module-sqlexplorer/releases/tag/v1.10) release.

**Comment by amarildosertorio** [comment]
Thank you, my friend!
