### ISSUE TITLE
Access denied on preview , csv or configuration

### ISSUE THREAD

**Issue by searchma** [gr8b/zabbix-module-sqlexplorer#9]
I have zabbix version 6.4.13 and module v1.10 and I have permission (acess denied) error whenever I want to preview or download an csv. Admin is in SuperAdmin group .Same when clicking on the configuration:
![image](https://github.com/gr8b/zabbix-module-sqlexplorer/assets/166613376/21e21f75-2013-4c29-aeeb-be4e2635afa2)

![image](https://github.com/gr8b/zabbix-module-sqlexplorer/assets/166613376/1da010f8-7aec-47bd-97a8-7497bbdc174b)

**Comment by gr8b** [comment]
Fixed in [v1.11](/gr8b/zabbix-module-sqlexplorer/releases/tag/v1.11)

**Comment by searchma** [comment]
It works :)
Thank you .

**Comment by gr8b** [comment]
Configuration modal fails on Zabbix 7.0.0rc1
